### ISSUE TITLE
LED lights

### ISSUE THREAD

**Issue by cyroassis** [nikivanov/watney#1]
Do you think it's possible to set a GPIO pin to turn on and off some LED headlights?

**Comment by nikivanov** [comment]
I don't see why not. For simplicity, I powered the motor controller through Raspberry Pi's 5V pins. They are supposed to limit the current to 800mA. Using a cheap USB ammeter, I saw that the rover takes about 600-700mA while running at full speed, so you don't have a ton of wiggle room. Then again, if you stall the wheels, I saw consumption of up to 1.1A, which should have tripped RPI's 5V fuse. LEDs don't need much to run, so you should be ok.
