### ISSUE TITLE
Speech function?

### ISSUE THREAD

**Issue by farminguin** [nikivanov/watney#11]
Would it be possible to add eSpeak Text-To-Speech? Like a LM4871 audio amp ? Textbox on the web interface? Would be a great way to make it for of a telepresence bot. ..

**Comment by svasiliou** [comment]
There is a 2way-audio branch but need explanation and wiring management.

**Comment by nikivanov** [comment]
To get 2 way audio working, I had to switch to Arch Linux from Raspbian. The 2wayaudio branch isn't functional yet, so I'd avoid using it for now. Once it's ready, I'll release an SD card image along with BOM and 3d printed parts. Overall, the cost of adding 2 way audio is about $6 if you order from China (plus printed parts).

**Comment by nikivanov** [comment]
2 way audio has been implemented
