### ISSUE TITLE
When Backing off the Wireless Charger Watney will reboot instead of moving

### ISSUE THREAD

**Issue by rtaylo** [nikivanov/watney#15]
This little robot is amazing to drive around the house and I'm having a blast with it. The only issue I've found is that Watney will reboot when I attempt to back out of the wireless charging bay.  The result is that my rover is "stuck" on the charger without the ability to reverse. 

For reference I am using:
https://www.aliexpress.com/item/32969639665.html?spm=a2g0o.productlist.0.0.531ef69aoHasVM&algo_pvid=aed1da03-ca85-47b8-bb87-2ebd00ad7b16&algo_expid=aed1da03-ca85-47b8-bb87-2ebd00ad7b16-0&btsid=b98f799f-1fe1-4a06-955c-8edf754855bc&ws_ab_test=searchweb0_0,searchweb201602_4,searchweb201603_55

Based on reviews it looks like it fails to work as a UPS.

**Comment by rtaylo** [comment]
To resolve the issue I purchased this: 
https://www.ebay.com/itm/352777629993

As it looks identical to what's pictured in the build guide.

**Comment by nikivanov** [comment]
Yep, getting the EXACT board is essential. I'll update the README with a note of which board not to get. Thanks!
