### ISSUE TITLE
Running new firmware on Watney 2.0?

### ISSUE THREAD

**Issue by rtaylo** [nikivanov/watney#26]
Is it possible to run the latest Watney build on Watney 2.0?
I have some SK9822 LEDs I ordered for my new Watney and I wanted to retrofit them on my older Watney 2.0

**Comment by nikivanov** [comment]
Not without some work, unfortunately. First, the new watney I2S for both playback and recording. This frees up PWM hardware so I can use it for hardware-timed PWM, so things like servos and motors dont have jitter. Additionally, im pretty sure the code will crash if it can't talk to the new UPS over I2C. You can definitely make it work, but it'll require some effort.
