### ISSUE TITLE
Feature request: Additional servo control

### ISSUE THREAD

**Issue by sarreck** [nikivanov/watney#30]
Hi,

Thank you for the great project. 

It would be really useful if there was an additional preconfigured servo PIN to allow additional functionality (e.g. left/right camera, turret or RC LED control).

There would also need to be associated keyboard keys for the web UI.

In my case I want to control a RC car type LED which is controlled as a servo (works fine when connected to the camera servo in testing)

![PXL_20220405_015205757](https://user-images.githubusercontent.com/6550017/162599294-38d3d6bb-ca10-4b9f-8920-67ef4658aacc.jpg)

Thank you for considering this.

**Comment by nikivanov** [comment]
Hi! To confirm, it sounds like you want another servo control bound to a new pair of keys. Is that correct?

**Comment by nikivanov** [comment]
Do you know how to code? I can point you to a few files that you'd need to modify to make this happen.

**Comment by sarreck** [comment]
> Hi! To confirm, it sounds like you want another servo control bound to a new pair of keys. Is that correct?

Yes thats correct.

**Comment by sarreck** [comment]
> Do you know how to code? I can point you to a few files that you'd need to modify to make this happen.

I have tried based on your response to an older issue, however I was not able to get it to work as I didn't really know what I was doing.

**Comment by nikivanov** [comment]
It shouldnt be difficult. I'll create a new branch and you should be able to copy the new files. I'll let you know when it's ready for you to test.

**Comment by sarreck** [comment]
Thank you, I appreciate it.

**Comment by nikivanov** [comment]
Hey @sarreck! I've made a new branch for your auxiliary servo. You can find here it: https://github.com/nikivanov/watney/tree/auxservo

By default the aux servo is on pin 6 and up/down is D / C

**Comment by sarreck** [comment]
Thanks, that works great!
