### ISSUE TITLE
Anyway to Change the TTS Engine?

### ISSUE THREAD

**Issue by rtaylo** [nikivanov/watney#31]
I liked the old Watney 2.0 voice, any way to switch back?

**Comment by nikivanov** [comment]
I think this should work:

Here's the command that the new Watney executes to get it to say things:
https://github.com/nikivanov/watney/blob/master/rover.conf#L53

Here's the command that the old Watney executes to get it to say things:
https://github.com/nikivanov/watney/blob/2.0/rover.conf#L45

It might be as simple as replacing the command in the rover.conf with the old command. You'd also have to install espeak:
```
sudo apt-get install espeak
```

**Comment by rtaylo** [comment]
Excellent! That worked
